Fix documentation for updating tags.
Trying to use the method documented does not work; Tag inherits
from dict and defines no 'update' method of its own, resulting in
a stack trace like:

➜  ~  python tag.py
Traceback (most recent call last):
  File tag.py, line 15, in <module>
    emails=list(emails))
TypeError: descriptor 'update' requires a 'dict' object but received a 'str'